from __future__ import annotations

from typing import Any, Dict, List


def _get_framework(payload: Dict[str, Any]) -> str:
    blueprint = payload.get("blueprint") or {}
    frontend = blueprint.get("frontend") or {}
    raw = str(frontend.get("framework") or "")
    return raw.strip().lower()


def _react_native_files(blueprint: Dict[str, Any]) -> List[Dict[str, str]]:
    name = str(blueprint.get("name") or blueprint.get("id") or "Velu App")
    slug = name.lower().replace(" ", "-")
    app_json = {
        "path": "mobile/react_native/app.json",
        "content": (
            "{\n"
            '  "expo": {\n'
            f'    "name": "{name}",\n'
            f'    "slug": "{slug}",\n'
            '    "version": "1.0.0"\n'
            "  }\n"
            "}\n"
        ),
    }
    package_json = {
        "path": "mobile/react_native/package.json",
        "content": (
            "{\n"
            f'  "name": "{slug}",\n'
            '  "version": "1.0.0",\n'
            '  "private": true,\n'
            '  "main": "index.js",\n'
            '  "dependencies": {\n'
            '    "expo": "^51.0.0",\n'
            '    "react": "^18.0.0",\n'
            '    "react-native": "0.74.0"\n'
            "  },\n"
            '  "scripts": {\n'
            '    "start": "expo start",\n'
            '    "android": "expo run:android",\n'
            '    "ios": "expo run:ios"\n'
            "  }\n"
            "}\n"
        ),
    }
    app_tsx = {
        "path": "mobile/react_native/App.tsx",
        "content": (
            'import React from "react";\n'
            'import { SafeAreaView, Text } from "react-native";\n'
            "\n"
            "export default function App() {\n"
            "  return (\n"
            "    <SafeAreaView>\n"
            f"      <Text>{name}</Text>\n"
            "    </SafeAreaView>\n"
            "  );\n"
            "}\n"
        ),
    }
    return [app_json, package_json, app_tsx]


def _flutter_files(blueprint: Dict[str, Any]) -> List[Dict[str, str]]:
    name = str(blueprint.get("name") or blueprint.get("id") or "Velu App")
    slug = name.lower().replace(" ", "_")
    pubspec = {
        "path": "mobile/flutter/pubspec.yaml",
        "content": (
            f"name: {slug}\n"
            "description: A mobile app generated by Velu\n"
            "version: 1.0.0+1\n"
            "\n"
            "environment:\n"
            "  sdk: '>=3.0.0 <4.0.0'\n"
            "\n"
            "dependencies:\n"
            "  flutter:\n"
            "    sdk: flutter\n"
            "\n"
            "flutter:\n"
            "  uses-material-design: true\n"
        ),
    }
    main_dart = {
        "path": "mobile/flutter/lib/main.dart",
        "content": (
            "import 'package:flutter/material.dart';\n"
            "\n"
            "void main() {\n"
            "  runApp(const VeluApp());\n"
            "}\n"
            "\n"
            "class VeluApp extends StatelessWidget {\n"
            "  const VeluApp({super.key});\n"
            "\n"
            "  @override\n"
            "  Widget build(BuildContext context) {\n"
            "    return MaterialApp(\n"
            f"      title: '{name}',\n"
            "      home: const Scaffold(\n"
            "        body: Center(\n"
            "          child: Text('Hello from Velu mobile'),\n"
            "        ),\n"
            "      ),\n"
            "    );\n"
            "  }\n"
            "}\n"
        ),
    }
    return [pubspec, main_dart]


def handle(payload: Dict[str, Any]) -> Dict[str, Any]:
    blueprint = payload.get("blueprint") or {}
    framework = _get_framework(payload)

    files: List[Dict[str, str]] = []

    if framework in {"react_native", "expo"}:
        files.extend(_react_native_files(blueprint))
    if framework == "flutter":
        files.extend(_flutter_files(blueprint))

    ok = bool(files)

    return {
        "ok": ok,
        "kind": "mobile_scaffold",
        "framework": framework,
        "files": files,
    }
