# services/agents/ui_scaffold.py
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from services.plugins import PLUGINS  # noqa: F401

logger = logging.getLogger(__name__)

_TPL = Path("templates")
DEFAULT_LOCALES = ["en", "fr", "nl", "de", "ar", "ta"]

# Where UI output should land so packager includes it.
# For Next.js we write into generated/web (not repo-root web/)
NEXTJS_BASE = "generated/web"
NEXTJS_BASE_COMPAT = "web"


LOGIN_PAGE_TSX = """import { FormEvent, useState } from "react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">(
    "idle",
  );
  const [message, setMessage] = useState("");

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();
    setStatus("loading");
    setMessage("");

    const base =
      process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000/api";

    try {
      const res = await fetch(`${base}/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        const detail = (body && (body.detail || body.error)) || "Login failed";
        throw new Error(detail);
      }

      const data = await res.json();
      setStatus("done");
      setMessage(`Logged in as ${data.email || email}`);
    } catch (err: any) {
      setStatus("error");
      setMessage(err?.message || "Login failed");
    }
  }

  return (
    <main
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#f1f5f9",
        padding: 16,
      }}
    >
      <section
        style={{
          width: "100%",
          maxWidth: 420,
          background: "white",
          borderRadius: 16,
          padding: 24,
          boxShadow: "0 10px 25px rgba(15, 23, 42, 0.08)",
        }}
      >
        <h1 style={{ marginTop: 0, marginBottom: 4 }}>Login</h1>
        <p style={{ marginTop: 0, fontSize: 14, color: "#4b5563" }}>
          Simple login form generated by Velu. It calls the{" "}
          <code>/auth/login</code> API of your backend.
        </p>

        <form
          onSubmit={handleSubmit}
          style={{ marginTop: 16, display: "grid", gap: 12 }}
        >
          <div>
            <label style={{ display: "block", fontSize: 13, marginBottom: 4 }}>
              Email
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              style={{
                width: "100%",
                padding: "8px 10px",
                borderRadius: 8,
                border: "1px solid #e5e7eb",
              }}
            />
          </div>
          <div>
            <label style={{ display: "block", fontSize: 13, marginBottom: 4 }}>
              Password
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              style={{
                width: "100%",
                padding: "8px 10px",
                borderRadius: 8,
                border: "1px solid #e5e7eb",
              }}
            />
          </div>
          <button
            type="submit"
            disabled={status === "loading"}
            style={{
              marginTop: 4,
              padding: "8px 12px",
              borderRadius: 999,
              border: "none",
              background: "#2563eb",
              color: "white",
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            {status === "loading" ? "Signing in…" : "Sign in"}
          </button>
        </form>

        {message && (
          <p
            style={{
              marginTop: 12,
              fontSize: 13,
              color: status === "error" ? "#b91c1c" : "#15803d",
            }}
          >
            {message}
          </p>
        )}
      </section>
    </main>
  );
}
"""

LANGUAGES_PAGE_TSX = """import { useEffect, useState } from "react";

type LocalesFile = {
  locales?: string[];
};

export default function LanguagesPage() {
  const [locales, setLocales] = useState<string[]>(["en"]);
  const [error, setError] = useState("");

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/i18n.locales.json");
        if (!res.ok) {
          throw new Error("http");
        }
        const data: LocalesFile = await res.json();
        if (Array.isArray(data.locales) && data.locales.length > 0) {
          setLocales(data.locales.map(String));
          return;
        }
      } catch {
        setError("Could not load locales file, using a single-language fallback.");
        setLocales(["en"]);
      }
    }
    load();
  }, []);

  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "2rem 1.5rem",
        maxWidth: "720px",
        margin: "0 auto",
        fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
      }}
    >
      <header style={{ marginBottom: "1.75rem" }}>
        <p
          style={{
            fontSize: "0.85rem",
            textTransform: "uppercase",
            letterSpacing: "0.15em",
            color: "#6b7280",
            marginBottom: "0.5rem",
          }}
        >
          Languages
        </p>
        <h1 style={{ fontSize: "2rem", fontWeight: 700, marginBottom: "0.25rem" }}>
          Supported languages
        </h1>
        <p style={{ color: "#4b5563", maxWidth: "32rem" }}>
          This page reads the <code>i18n.locales.json</code> file and shows the configured
          language codes.
        </p>
      </header>

      <section
        style={{
          borderRadius: "1rem",
          border: "1px solid #e5e7eb",
          padding: "1.5rem",
          background: "white",
          boxShadow: "0 4px 12px rgba(15,23,42,0.04)",
        }}
      >
        {error && (
          <p style={{ color: "#b91c1c", fontSize: "0.9rem", marginBottom: "0.75rem" }}>
            {error}
          </p>
        )}

        <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
          {locales.map((code) => (
            <li
              key={code}
              style={{
                padding: "0.5rem 0.75rem",
                borderRadius: "0.6rem",
                border: "1px solid #e5e7eb",
                marginBottom: "0.5rem",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                fontSize: "0.95rem",
              }}
            >
              <span style={{ fontWeight: 500 }}>{code}</span>
              <span
                style={{
                  fontSize: "0.8rem",
                  padding: "0.2rem 0.5rem",
                  borderRadius: "999px",
                  background: "#eff6ff",
                  color: "#1d4ed8",
                }}
              >
                Enabled
              </span>
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}
"""

def _read(p: Path, default: str = "") -> str:
    try:
        return p.read_text(encoding="utf-8")
    except Exception as exc:
        logger.debug("ui_scaffold: failed to read %s: %s", p, exc)
        return default

def _extract_locales_from_blueprint(bp: Any) -> list[str] | None:
    if isinstance(bp, dict):
        loc = bp.get("localization") or {}
        if isinstance(loc, dict):
            supported = loc.get("supported_languages")
            default = loc.get("default_language")
            out: list[str] = []
            if isinstance(supported, (list, tuple)):
                out = [str(x) for x in supported if str(x).strip()]
            if not out and isinstance(default, str) and default.strip():
                out = [default.strip()]
            return out or None

    localization = getattr(bp, "localization", None)
    if localization is not None:
        supported = getattr(localization, "supported_languages", None)
        default = getattr(localization, "default_language", None)
        out: list[str] = []
        if isinstance(supported, (list, tuple)):
            out = [str(x) for x in supported if str(x).strip()]
        if not out and isinstance(default, str) and default.strip():
            out = [default.strip()]
        return out or None

    return None

def _extract_locales(payload: dict[str, Any]) -> list[str]:
    ui_langs = payload.get("ui_languages")
    if isinstance(ui_langs, (list, tuple)) and ui_langs:
        return [str(x) for x in ui_langs if str(x).strip()]

    bp = payload.get("blueprint")
    if bp is not None:
        from_bp = _extract_locales_from_blueprint(bp)
        if from_bp:
            return from_bp

    raw_locales = payload.get("locales")
    if isinstance(raw_locales, (list, tuple)) and raw_locales:
        return [str(x) for x in raw_locales if str(x).strip()]

    product = payload.get("product")
    if isinstance(product, dict):
        prod_locales = product.get("locales")
        if isinstance(prod_locales, (list, tuple)) and prod_locales:
            return [str(x) for x in prod_locales if str(x).strip()]

    return DEFAULT_LOCALES

def _resolve_frontend(payload: dict[str, Any]) -> str:
    bp = payload.get("blueprint")
    if bp is not None:
        if isinstance(bp, dict):
            f_stack = bp.get("frontend") or {}
            if isinstance(f_stack, dict):
                fw = f_stack.get("framework")
                if isinstance(fw, str) and fw.strip():
                    return fw.strip().lower()
        else:
            frontend = getattr(bp, "frontend", None)
            if frontend is not None:
                fw = getattr(frontend, "framework", None)
                if isinstance(fw, str) and fw.strip():
                    return fw.strip().lower()

    raw = payload.get("frontend") or "nextjs"
    return str(raw).strip().lower() or "nextjs"

def handle(payload: dict[str, Any]) -> dict[str, Any]:
    files: list[dict[str, str]] = []

    frontend = _resolve_frontend(payload)
    locales = _extract_locales(payload)

    raw_plugins = payload.get("plugins") or []
    plugins: set[str] = set()
    if isinstance(raw_plugins, (list, tuple, set)):
        for p in raw_plugins:
            text = str(p or "").strip().lower()
            if text:
                plugins.add(text)
    has_auth = "auth" in plugins

    plugin_frontend_tags: set[str] = set()
    for slug in plugins:
        plugin = PLUGINS.get(slug)
        if plugin:
            plugin_frontend_tags.update(plugin.frontend_tags)

    # --- Next.js output goes into generated/web so it is packaged ---
    if frontend in {"nextjs", "next", "next.js"}:
        index_tpl = _read(
            _TPL / "next_index.tsx.j2",
            "export default function Home(){\n  return <div>Hello Velu</div>\n}\n",
        ).replace("{{ headline }}", "Multi-language dashboard")

        # pages
        files.append({"path": f"{NEXTJS_BASE}/pages/index.tsx", "content": index_tpl})
        files.append({"path": f"{NEXTJS_BASE_COMPAT}/pages/index.tsx", "content": index_tpl})

        pkg = '{\n  "name": "generated-web",\n  "private": true\n}\n'
        files.append({"path": f"{NEXTJS_BASE}/package.json", "content": pkg})
        files.append({"path": f"{NEXTJS_BASE_COMPAT}/package.json", "content": pkg})

        web_locales_json = json.dumps({"locales": locales}, indent=2)
        files.append({"path": f"{NEXTJS_BASE}/i18n.locales.json", "content": web_locales_json + "\n"})
        files.append({"path": f"{NEXTJS_BASE_COMPAT}/i18n.locales.json", "content": web_locales_json + "\n"})

        files.append({"path": f"{NEXTJS_BASE}/pages/languages.tsx", "content": LANGUAGES_PAGE_TSX})
        files.append({"path": f"{NEXTJS_BASE_COMPAT}/pages/languages.tsx", "content": LANGUAGES_PAGE_TSX})

        if has_auth:
            files.append({"path": f"{NEXTJS_BASE}/pages/login.tsx", "content": LOGIN_PAGE_TSX})
            files.append({"path": f"{NEXTJS_BASE_COMPAT}/pages/login.tsx", "content": LOGIN_PAGE_TSX})


        return {
            "ok": True,
            "agent": "ui_scaffold",
            "files": files,
            "frontend": frontend,
            "locales": locales,
            "plugin_frontend_tags": sorted(plugin_frontend_tags),
        }

    # --- React SPA stays in react_spa/ ---
    if frontend == "react":
        react_pkg = json.dumps(
            {
                "name": "react-spa",
                "version": "0.0.1",
                "private": True,
                "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                },
                "dependencies": {
                    "react": "^18.0.0",
                    "react-dom": "^18.0.0",
                },
                "devDependencies": {
                    "vite": "^5.0.0",
                    "@vitejs/plugin-react-swc": "^3.0.0",
                },
            },
            indent=2,
        )
        files.append({"path": "react_spa/package.json", "content": react_pkg + "\n"})

        vite_config = (
            'import { defineConfig } from "vite";\n'
            'import react from "@vitejs/plugin-react-swc";\n\n'
            "export default defineConfig({\n"
            "  plugins: [react()],\n"
            "});\n"
        )
        files.append({"path": "react_spa/vite.config.js", "content": vite_config})

        index_html = """<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>React multi-language demo</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""
        files.append({"path": "react_spa/index.html", "content": index_html})

        main_jsx = """import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
"""
        files.append({"path": "react_spa/src/main.jsx", "content": main_jsx})

        index_css = """body {
  margin: 0;
  font-family: system-ui, sans-serif;
  background: #f1f5f9;
}
"""
        files.append({"path": "react_spa/src/index.css", "content": index_css})

        react_locales_json = json.dumps({"locales": locales}, indent=2)
        files.append({"path": "react_spa/i18n.locales.json", "content": react_locales_json + "\n"})
        files.append({"path": f"{NEXTJS_BASE_COMPAT}/i18n.locales.json", "content": react_locales_json + "\n"})

        # Minimal App.jsx
        app_jsx = """import { useEffect, useState } from "react";
import "./index.css";

export default function App() {
  const [locales, setLocales] = useState(["en"]);
  const [current, setCurrent] = useState("en");

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/i18n.locales.json");
        const data = await res.json();
        const raw = Array.isArray(data.locales) ? data.locales : [];
        if (raw.length > 0) {
          const norm = raw.map((x) => String(x));
          setLocales(norm);
          setCurrent(norm[0]);
        }
      } catch {
        setLocales(["en"]);
        setCurrent("en");
      }
    }
    load();
  }, []);

  return (
    <main style={{ minHeight: "100vh", background: "#f1f5f9", padding: 16 }}>
      <section style={{ maxWidth: 680, margin: "0 auto", background: "white", borderRadius: 16, padding: 16, border: "1px solid #e5e7eb" }}>
        <h1 style={{ marginTop: 0 }}>React multi-language demo</h1>
        <p style={{ fontSize: 14, color: "#4b5563" }}>
          React SPA scaffold generated by Velu.
        </p>

        <div style={{ marginTop: 12 }}>
          <label style={{ fontSize: 13 }}>Locale</label>
          <div>
            <select value={current} onChange={(e) => setCurrent(e.target.value)} style={{ marginTop: 4, padding: "4px 8px" }}>
              {locales.map((code) => (
                <option key={code} value={code}>{code}</option>
              ))}
            </select>
          </div>
        </div>
      </section>
    </main>
  );
}
"""
        files.append({"path": "react_spa/src/App.jsx", "content": app_jsx})

        return {
            "ok": True,
            "agent": "ui_scaffold",
            "files": files,
            "frontend": frontend,
            "locales": locales,
            "plugin_frontend_tags": sorted(plugin_frontend_tags),
        }

    # Default: return something predictable even if unknown frontend
    return {
        "ok": True,
        "agent": "ui_scaffold",
        "files": [],
        "frontend": frontend,
        "locales": locales,
        "plugin_frontend_tags": sorted(plugin_frontend_tags),
    }
