services:
  api:
    image: velu-api:local
    user: "10001:10001"
    command: >
      uvicorn services.app_server.main:create_app
      --factory --host 0.0.0.0 --port 8010 --log-level info
    environment:
      API_KEYS: ${API_KEYS:-local}
      TASK_DB: /data/jobs.db
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost,http://127.0.0.1}
    ports:
      - "127.0.0.1:8081:8010"
    restart: unless-stopped
    read_only: true
    tmpfs: ["/tmp"]
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8010/ready >/dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s

  worker:
    image: velu-worker:local
    user: "10001:10001"
    command:
      - python
      - -c
      - |
        import sys, importlib
        sys.path[:0] = ['/app', '/app/src']
        import sitecustomize
        importlib.import_module('services.queue.worker_entry').main()
    environment:
      TASK_DB: /data/jobs.db
      WORKER_ENABLE_PIPELINE: ${WORKER_ENABLE_PIPELINE:-1}
      WORKER_MAX_JOBS: ${WORKER_MAX_JOBS:-0}
      WORKER_POLL_SECONDS: ${WORKER_POLL_SECONDS:-1}
    restart: unless-stopped
    read_only: true
    tmpfs: ["/tmp"]
    volumes:
      - ./data:/data
      - ./data/git:/git
      - ./data/generated:/app/generated
      - ./data/tests:/app/tests
    depends_on:
      api:
        condition: service_healthy

  data_init:
    image: busybox:1.36
    user: "0:0"
    command: >
      sh -c "mkdir -p /data /git && chown -R 10001:10001 /data /git && chmod -R u+rwX /data /git"
    volumes:
      - ./data:/data
      - ./data/git:/git
    restart: "no"
